export { default as attachmentService } from './attachmentService'
export { default as dictService } from './dictService'
export { default as orgService } from './orgService'
export { default as userService } from './userService'
export { default as wxworkService } from './wxworkService'
